# Generated by Django 3.1.5 on 2021-10-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_date1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя вакцинация (дата 1)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_date2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя вакцинация (дата 2)'),
        ),
    ]
