# Generated by Django 3.1.5 on 2021-10-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20211019_0754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('last_name',), 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_date1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя вакцинация (дата 1)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_date2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя вакцинация (дата 2)'),
        ),
    ]
