# Generated by Django 3.1.5 on 2021-10-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_cadet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecadet',
            name='is_willing',
            field=models.BooleanField(default=False, verbose_name='Желает пройти вакцинацию'),
        ),
    ]
