# Generated by Django 3.1.5 on 2021-10-19 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0005_auto_20211019_0757'),
        ('covid_cadet', '0003_auto_20211019_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField(blank=True, null=True, verbose_name='Дата проведения первой вакцинации')),
                ('date2', models.DateField(blank=True, null=True, verbose_name='Дата проведения второй вакцинации')),
                ('add_date_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего редактирования')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_cadet.employeecadet', verbose_name='Сотрудник/курсант')),
                ('vaccine_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadet_vaccine_kind', to='covid.vaccinekind', verbose_name='Вид вакцины')),
            ],
            options={
                'verbose_name': 'Курс вакцинации',
                'verbose_name_plural': '5. Курсы вакцинации',
                'ordering': ('id',),
            },
        ),
    ]
